---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 'maven'
    tag: '3-jdk-8'

inputs:
  - name: source-code

run:
  path: /bin/bash
  args:
  - -exc
  - |
    cd source-code
    mvn --version
    mvn clean package
